### ISSUE TITLE
Remove SEQC2 on About page

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco-public-website#13]
The [SEQC2](https://accessdata-preprod.fda.gov/scripts/FDATrack/view/track_project.cfm?program=nctr&id=NCTR-DBB-PM-SEQC2-Phase-II) link on the [About](https://condescending-leakey-26b782.netlify.app/about/) page is broken, so I removed it.

**Comment by kee007ney** [comment]
Approved.
